# Generated by Django 2.2.16 on 2022-11-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_auto_20221116_0728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=120, unique=True, verbose_name="Cлаг"
            ),
        ),
    ]
